-- ============================================================
-- Storage bucket: photos
-- Private bucket — all access via signed URLs generated by
-- the gallery Edge Function. Guests upload directly from the
-- client using their anonymous auth session.
-- ============================================================
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'photos',
  'photos',
  false,
  5242880,  -- 5 MB max per photo (client compresses to ~1200px JPEG 80%)
  array['image/jpeg', 'image/jpg', 'image/webp']
)
on conflict (id) do nothing;

-- ============================================================
-- Storage RLS policies
-- Path pattern: {sessionId}/{guestId}/{course}.jpg
-- Guests upload to their own path. Service role reads all
-- (for signed URL generation in the gallery Edge Function).
-- ============================================================

-- Guests can upload photos to their own folder only.
-- Path must start with {sessionId}/{auth.uid()}/
create policy "storage_photos_insert_own"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'photos'
    and (storage.foldername(name))[2] = auth.uid()::text
  );

-- Guests can read their own photos (for preview after upload).
create policy "storage_photos_read_own"
  on storage.objects for select
  to authenticated
  using (
    bucket_id = 'photos'
    and (storage.foldername(name))[2] = auth.uid()::text
  );

-- Guests can replace (update) their own photos (retake flow).
create policy "storage_photos_update_own"
  on storage.objects for update
  to authenticated
  using (
    bucket_id = 'photos'
    and (storage.foldername(name))[2] = auth.uid()::text
  );
